spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://182.160.3.202:3306/eleco?useUnicode=true & characterEncoding=utf-8 &
      useSSL=true & serverTimezone=Asia/Shanghai
    username: root
    password: root
  mvc:
    hiddenmethod:
      filter:
        enabled: true
#  http:
#    multipart:
#      enabled: true
#      max-file-size: 30MB
#      max-request-size: 30MB

swagger:
  enable: true
